spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
        url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
        username: root
        password: Etr12345
        initialization-mode: always

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

    mail:
      host: localhost
      port: 25
      protocol: smtp
#      username: USERNAME@gmail.com
#      password: PASSWORD
      properties:
        mail:
          smtps:
            auth: false
            timeout: 8000
#            starttls:
#              enable: true
          transport:
            protocol: smtps

    main:
      allow-bean-definition-overriding: true
# --- server
server:
  port: 8081
support:
  mail: tahminApp